CREATE DATABASE trivia;
CREATE DATABASE trivia_test;
GRANT ALL PRIVILEGES ON DATABASE trivia TO postgres;
GRANT ALL PRIVILEGES ON DATABASE trivia_test TO postgres;
ALTER USER postgres CREATEDB;
ALTER USER postgres WITH SUPERUSER;